### PR TITLE
add p700 support

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by DHOMD** [comment]
Im happy to add this, but I do not see any p700 support since 4.0.4
(BTW your fingerprints need updating)

There is no guarantees this can be brought to 4.3.  Do you have any device/lge/p700 repos in mind?

**Comment by DHOMD** [comment]
Ahh nm I see then in your git

Cool.

**Comment by ghost** [comment]
I alread have a set of almost stable build of vanir, this is just easier with syncing

**Comment by ghost** [comment]
see this https://github.com/TeamHackLG
http://forum.xda-developers.com/showthread.php?t=2433625

**Comment by DHOMD** [comment]
Very nice

:)

Just need to merge the manifest + vendor files and should be go-to-go

**Pull request merged**
